# Generated by Django 3.2.5 on 2023-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('months', models.PositiveIntegerField()),
                ('percentage', models.PositiveIntegerField()),
                ('minimum_money', models.PositiveIntegerField()),
                ('maximum_money', models.PositiveIntegerField()),
            ],
        ),
    ]
